#+TITLE: Overpass
#+AUTHOR: siiky
#+DATE: 2022/03/26
#+LANGUAGE: en

/Overpass/ is an interface used to query OSM data. /Overpass Turbo/ is an
Overpass web client you can use to query OSM data, export it, &c.

Some links:

+ Overpass Turbo ::
 - https://overpass-turbo.eu
 - https://wiki.openstreetmap.org/wiki/Overpass_turbo
+ Overpass Query Language :: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL
+ Overpass API :: https://wiki.openstreetmap.org/wiki/Overpass_API

-----

* Useful Queries

This is a list of useful queries I've learned over time.

** Features last modified by an user

Nodes, ways, or relations last modified by "user name":

#+BEGIN_SRC txt
nwr(user:"user name")({{bbox}});
out body;
#+END_SRC

** Features modified between two dates

Node, way, or relation amenities modified between 2022-02-04T00:00:00Z and
"to-date":

#+BEGIN_SRC txt
// The to-date is optional and defaults to now
[diff:"2022-02-04T00:00:00Z","to-date"];
nwr["amenity"]({{bbox}});
out body;
#+END_SRC

** Features around other features

Picnic sites within a 1km radius of restaurants with takeaway:

#+BEGIN_SRC txt
node[amenity=restaurant][takeaway=yes]({{bbox}});
node(around:1000)[tourism=picnic_site];
out body;
#+END_SRC

** Features inside some area object

Libraries in Portugal:

#+BEGIN_SRC txt
nwr["amenity"="library"](area:3600295480);
out body;

// Or:

area(3600295480)->.searchArea;
(nwr["amenity"="library"](area.searchArea););
out body;
>;
out skel qt;
#+END_SRC

I don't understand the difference between the two yet, but the latter is
supposed to be more correct. All I know is that ~>;~ is supposed to make the
query recursive.

The explanation of the ~area:XXX~ from [[https://stackoverflow.com/a/65982945][this StackOverflow answer]]:

#+BEGIN_QUOTE
If the polygon you want to query inside of is an OSM feature, you can also query
using an area ID.

Area IDs are generated by the Overpass server to make querying data within
existing polygons easier. You can determine the area ID for a way by adding
2400000000 to the way ID and the area ID for a relation by adding 3600000000 to
the relation ID (assuming that the way or relation is a valid area feature).
#+END_QUOTE

I found [[https://www.openstreetmap.org/relation/295480][Portugal's relation object]], which is the relation =295480=, and
=3600000000 + 295480 = 3600295480=.
