#+TITLE: Fagot
#+AUTHOR: siiky
#+DATE: 2022/05/05
#+LANGUAGE: en

After some recent events in my personal life [[https://en.wikipedia.org/wiki/Ran_(film)][/乱/ (/Ran/)]] came to mind: what if
our "mental strength", or ability to withstand stress, is like a [[https://www.merriam-webster.com/dictionary/fagot][fagot]] of
arrows?

I think the analogy works well enough.

**DISCLAIMER:** I haven't the faintest fucking clue what I'm talking about. All
that I "know" about psychology is from /Psych 101/ by Paul Kleinman (maybe
others meanwhile, check my [[file:/books/list.html][book list]]), random Wikipedia pages, and a few random
posts here and there. I just had this thought after the already mentioned events
and decided meditate on it.

* The Analogy

One arrow corresponds to one "unit" of "mental strength".

Greater number of arrows translates to increased ability to withstand stress,
and vice versa, lesser number, decreased ability.

Repeated or continuous stress on the fagot eventually results in breakdown,
assuming that the stress actually strains at least some of the arrows.

And rest, that is, lack of stress or strain, has some sort of "healing" effect.
Immediatly after you've gone through some stressful event you're more likely to
breakdown with another stressful event. However, give it some time and the
second event is more maneageable. This is possibly the case that translates
worse. If an arrow starts to crack it won't magically uncrack. But maybe that's
the wrong scale to think about -- arrows can be very flexible, so they can
withstand a lot of stress in a very short interval with no damage (their "stress
capacity" depletes as fast as it regenerates). On the other hand, if they are
cracked, they have to be replaced -- maybe like sharks replace their teeth? Or
maybe the analogy plays perfectly right, and there's no way to fix a broken
fagot... shit, fingers crossed!

And lastly: two fagots are indistinguishable if not under stress. 20 arrows
suspended in the air, or simply resting in your hands, don't break by themselves
-- you have a literal emergency in your hands if they do. But the same is true
for one single arrow -- it will comfortably withstand the atmospheric pressure.
However, try to bend them or hang something at the tip, and the difference will
be noticeable. This means that unless you're under stress you can't know how
much stress you can really handle. And also that you can't compare two different
people in terms of their "mental strength" without putting them under stress.

* Fagot of Fagots

Now, how does this fit into the mind of some person?

The way I see it, there isn't one single fagot to take it all. It seems more
natural to me that there are several fagots, each with a different "purpose", or
for a different kind of aspect of life or relationship.

Why I think that's the case: if I have a shit day at work, I won't feel stressed
with University because of it -- and vice versa. Another example, probably more
obviously: if I have a fight with someone, let's say a really ugly one, I won't
feel stressed talking with someone else because of it; or I won't feel ill with
that someone else because of it. SG(e)TM!

So there's at least some fagot of fagots. Maybe it's really an hierarchy:
there's the main fagot, composed of the society/work fagot, the
learning/University fagot, the personal life fagot, the general life fagot, ...

The society/work fagot may be split into the "social status" fagot, money fagot,
career fagot (kinda tied to "social status"), ...

The learning/University fagot may be split into the self-learning fagot (the
shit you like/want to learn), the research fagot (the shit the scientific
community thinks is dope), the grades fagot (the shit grades you get at
classes), ...

The personal life fagot may be split into a fagot for each relationship with a
person, which includes the auto-fagot.

* Main Fagot Breakdown

There's just this something I still can't explain, and that doesn't seem to
translate well through the /Fagot Hierarchy Theory/ I described above: what
would bring one to the point of suicide?

From the theory it seems that suicide shouldn't even be considered unless the
main fagot breaks -- all the fagots under it break? But I don't think that one
would bring oneself to this point because of just one fagot either.

So what's it take?

* How One Fagot Affects Another

Could it be that different fagots have different strengths? Such that, for
example, the main fagot's main source of strength comes from, let's say, the
work fagot. In this case, if the work fagot goes to shit, the littlest strain on
the other fagots could be enough to break them, and thus break the main fagot as
well.

Almost as if the strain "leaked" from one fagot to the other.

* How Better Fagots Become

How fagots get weakened it's already been discussed. But how do we get to
withstand higher levels of strain with time? Dunno...

Do we really become stronger and capable of taking more stress, or do we become
"numb" and stop feeling that we're under stress?

Is it like sleep and caffeine? Do we think we're fine until we start to really
feel the effects of the lack of sleep?
