#+TITLE: Flexibility & Life
#+AUTHOR: siiky
#+DATE: 2022/06/01
#+LANGUAGE: en

To be able to [[file:/psychology/fagot.html][withstand the punches life throws at you]], being flexible is
helpful, methinks. It allows you to focus on what matters to you, overlook what
doesn't, and to dodge them punches like a pro. Let me try to explain what I
mean.

-----

From my limitted knowledge of Chinese philosophy and martial arts philosophy,
before anything else, what you need most is flexibility.

From the [[file:/books/list.html][/Tao Te Ching/]] ([[https://en.wikipedia.org/wiki/Tao_Te_Ching][Wikipedia]]) (that I should reread some day in the near
future) the main takeway I got is that you'll have a hard time if you go against
nature -- certainly harder than if you go along it. If you're lucky (or maybe
strong enough? depending on your definition of strength), that's all it will be,
harder; more likely, however, you'll simply lose.

Thus, from my (very likely wrong and/or incomplete) understanding, the [[https://en.wikipedia.org/wiki/Tao][/Tao/]] is
to go with nature, accept nature, go with the flow, accept things as they are
and that they're rarely as you'd prefer them to be, that what happens through
your course of life will happen whether you like it or not, and that often you
have no say in it -- what will be, will be (this isn't some "fate" BS or /hard
determinism/, though it may look like it; more later).

A similar idea exists in [[https://en.wikipedia.org/wiki/Tai_chi][/Tai Chi/]] boxing, where you don't fight your oponent
with force, but by trying to deflect their attacks, or using their nature
against them.

And what better way is there to "go with the flow" than by being flexible in
your moves and in your mind?

-----

More practically (but not necessarily by the /Tao/) I think of it as avoiding
unnecessary (unnatural) imposed limits or goals; or as distilling what I really
enjoy from what I don't (as much). Such that I may focus what matters to me most
without getting overly lost on "trivialities".

For example, some decades ago someone /declared/ that "you must eat every 3h~4h
and must not go many hours without eating" (I can't remember who nor why; have
to research). Similarly, someone once /declared/ that "breakfast is the most
important meal of the day and so must also be the heaviest/fullest" (this one I
do remember: [[https://www.theguardian.com/lifeandstyle/2016/nov/28/breakfast-health-america-kellog-food-lifestyle][Kellogg's and some bacon company]]). I purposefully say "declared",
because this wasn't the result of some scientific study or some other method.
Saying a bunch of bullshit nobody listens to is quite alright -- no harm done,
right? The problem is that these "truths" are actually accepted as truths in (at
least some of) today's western society!

Let's imagine some scenarios:

 1. You feel hungry, but you don't eat (let's say because you can't).
 2. You don't feel hungry, and you don't eat (no matter why).
 3. You don't feel hungry, but you eat anyway.

I'm not talking here about people that actually suffer from hunger. I'm assuming
you're skipping only one, maybe two, meals at most. *Actually suffering from
hunger is serious, and I'm not trying in any way to downplay its seriousness!*

If you don't believe in any of the declared crap, all's fine, you just go on
with your day, in any of the 3 scenarios. But what if you do believe it?

In (1) and (2), what's actually worse for your health: the fact that you haven't
eaten, or that you're stressing because you believe it's bad you haven't eaten
(whether you feel hungry or not)?

In (1), what's worse: the fact that you haven't eaten, or that you're stressing
because you feel hungry (but can't eat)? Though stress does actual harm, I can't
empathize with this particular "pain". If you feel hungry but you can't eat
right now: yes, it's unpleasant, but STFU and suck it up! You're acting like a
spoiled kid. Many people in the world suffer from hunger for real, not you.
You're lucky you don't suffer from hunger, and you should appreciate that fact.

In (3) the food you have is arguably unnecessary -- your body didn't feel it
necessary, at least. And it may be extra food, that makes you fatter.

And particulars matter, of course. If you do hard physical work, skipping a meal
may be enough to have you pass out or something after a while. But many people
nowadays /don't/ do any hard physical work. And they eat *tons* of food. Food
that they don't need. For these many people, skipping a meal or even two, as
long as they don't start feeling weak or something, is very likely OK.

-----

This went a bit off-topic... To get back on track: in these scenarios, is the
food what really matters? This is possibly the most important question. I argue
that it *isn't*! You can survive the scenarios, easily! On top of that, *there's
nothing you can do right now* to improve the situation.

So what do you think the better use of your energy is: worrying about something
you can easily survive, or worrying about or enjoying something that matters to
you, something you like, something you want (not as short-term as food,
obviously)?

* The "fate" BS/hard determinism
