#+TITLE: Flexibility & Relations
#+AUTHOR: siiky
#+DATE: 2022/06/07
#+LANGUAGE: en

I recently wrote about how [[file:/philosophy/flexibility-life.html][flexibility may be beneficial in your course of life]].

I've thought some times in the past how after I present myself in some way, I
can no longer present myself some other (conflicting) way in the future to the
same person(s). At least not with some [[https://en.wikipedia.org/wiki/Friction][friction]].

In this post I'd like to write about that, yet another aspect of life where
flexibility can be useful (and possibly a hindrance!): human relations.

-----

I first came across a similar idea (maybe when I first thought about this, in
fact) reading one of [[https://en.wikipedia.org/wiki/Descartes][Descartes]]' [[file:/books/list.html][books]] -- either /Discourse on the Method/ or
/Selections from the Principles of Philosophy/, I can't remember. In that book
he wrote that there were works he didn't want to publish during his lifetime.¹
/Wut? why?/ He explains that his works were often controversial due to the
nature of their content -- religion and God were particularly controversial² --
and by not publishing them he could continue with his life and work without any
impediments (read: being imprisoned and/or killed).

-----

If you tell a friend one day that you like a nice and hot [[https://en.wikipedia.org/wiki/Churro][/churro/]] (or
[[https://en.wikipedia.org/wiki/Fartura_(food)][/fartura/]], the inferior alternative), you can't then tell them the next day that
you /don't/ like it, right? It doesn't make sense! It can look like you lied or
are lying now. And it applies to everything, not only food, obviously.

Think of [[https://en.wikipedia.org/wiki/Knowledge][knowledge]] as a ([[https://en.wikipedia.org/wiki/Consistent][consistent]] i.e. [[https://en.wikipedia.org/wiki/Contradiction][non-contradictory]]) set of [[https://en.wikipedia.org/wiki/Proposition][propositions]].
From this [[https://en.wikipedia.org/wiki/Point_of_view_(philosophy)][point of view]], acquiring knowledge is performing the [[https://en.wikipedia.org/wiki/Set_union][set-union]] of the
current propositions with the new. If a person knows that you like churros
(=P=), and learns later that you /don't/ like churros (=¬P=), their knowledge
becomes inconsistent: =P ∧ ¬P= is a contradiction!

Of course, people can change their opinions, tastes, and whatnot -- it was
supposed so just now -- but it's a slow process, slow enough not to be flexible.

/So, what's it mean?/ If you're of an opinion now that (you think) you're likely
to change in the future, then... maybe you're better off not sharing it with
others right now? Because, if you change opinion in the future, it'll take time
for people to adjust their knowledge set; people will judge you hard if said
opinion is controversial or doesn't go down their throats well; and, if you
change opinion in the future, whatever negative side-effects came of your
sharing it were most likely a net loss -- waste of time and energy, at best.

There's a caveat, though. I'm here advocating that it may be a good idea to
refrain from sharing details about yourself with other people -- and I don't
make any distinctions between close or not. But if you do it too much,
especially with a close relation, the other person won't know that much about
you, which may mean the relation isn't that great, and it may end because of it.

Just another tool in the toolbox... Maybe. Or not. ¯\__(ツ)_/¯

-----

¹ There are cons to this, such as not discussing with as many people, but he was
a pretty good thinker -- he had a strict method for reasoning, which was the
subject of one of the two books (probably /Discourse on the Method/ judging by
the title). On top of that (IIRC) he had a few close relations with whom to
discuss the more controversial topics.

² Not that they somehow went against the state of affairs of the time -- he
believed in God (one of them is supposed to be a proof it exists) and was
religious (even supported the church IIRC) -- but that they were such a
different way to look at and think of things, that people had to assume he was a
heretic when they didn't understand him -- and understanding him was no simple
task!
